/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWeeklyExpendituresRouteImport } from './routes/_authenticated/weekly-expenditures'
import { Route as AuthenticatedSystemResetRouteImport } from './routes/_authenticated/system-reset'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSavingsRouteImport } from './routes/_authenticated/savings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPassbookRouteImport } from './routes/_authenticated/passbook'
import { Route as AuthenticatedOpeningBalancesRouteImport } from './routes/_authenticated/opening-balances'
import { Route as AuthenticatedMyWeeklyRouteImport } from './routes/_authenticated/my-weekly'
import { Route as AuthenticatedMySavingsRouteImport } from './routes/_authenticated/my-savings'
import { Route as AuthenticatedMyPassbookRouteImport } from './routes/_authenticated/my-passbook'
import { Route as AuthenticatedMyLoansRouteImport } from './routes/_authenticated/my-loans'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated/loans'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedBenevolentRouteImport } from './routes/_authenticated/benevolent'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedLoansLoanIdRouteImport } from './routes/_authenticated/loans.$loanId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeeklyExpendituresRoute =
  AuthenticatedWeeklyExpendituresRouteImport.update({
    id: '/weekly-expenditures',
    path: '/weekly-expenditures',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemResetRoute =
  AuthenticatedSystemResetRouteImport.update({
    id: '/system-reset',
    path: '/system-reset',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSavingsRoute = AuthenticatedSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPassbookRoute = AuthenticatedPassbookRouteImport.update({
  id: '/passbook',
  path: '/passbook',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpeningBalancesRoute =
  AuthenticatedOpeningBalancesRouteImport.update({
    id: '/opening-balances',
    path: '/opening-balances',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyWeeklyRoute = AuthenticatedMyWeeklyRouteImport.update({
  id: '/my-weekly',
  path: '/my-weekly',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMySavingsRoute = AuthenticatedMySavingsRouteImport.update({
  id: '/my-savings',
  path: '/my-savings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyPassbookRoute = AuthenticatedMyPassbookRouteImport.update({
  id: '/my-passbook',
  path: '/my-passbook',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyLoansRoute = AuthenticatedMyLoansRouteImport.update({
  id: '/my-loans',
  path: '/my-loans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBenevolentRoute = AuthenticatedBenevolentRouteImport.update({
  id: '/benevolent',
  path: '/benevolent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoansLoanIdRoute =
  AuthenticatedLoansLoanIdRouteImport.update({
    id: '/$loanId',
    path: '/$loanId',
    getParentRoute: () => AuthenticatedLoansRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/benevolent': typeof AuthenticatedBenevolentRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/loans': typeof AuthenticatedLoansRouteWithChildren
  '/members': typeof AuthenticatedMembersRoute
  '/my-loans': typeof AuthenticatedMyLoansRoute
  '/my-passbook': typeof AuthenticatedMyPassbookRoute
  '/my-savings': typeof AuthenticatedMySavingsRoute
  '/my-weekly': typeof AuthenticatedMyWeeklyRoute
  '/opening-balances': typeof AuthenticatedOpeningBalancesRoute
  '/passbook': typeof AuthenticatedPassbookRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/savings': typeof AuthenticatedSavingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/system-reset': typeof AuthenticatedSystemResetRoute
  '/weekly-expenditures': typeof AuthenticatedWeeklyExpendituresRoute
  '/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/benevolent': typeof AuthenticatedBenevolentRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/loans': typeof AuthenticatedLoansRouteWithChildren
  '/members': typeof AuthenticatedMembersRoute
  '/my-loans': typeof AuthenticatedMyLoansRoute
  '/my-passbook': typeof AuthenticatedMyPassbookRoute
  '/my-savings': typeof AuthenticatedMySavingsRoute
  '/my-weekly': typeof AuthenticatedMyWeeklyRoute
  '/opening-balances': typeof AuthenticatedOpeningBalancesRoute
  '/passbook': typeof AuthenticatedPassbookRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/savings': typeof AuthenticatedSavingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/system-reset': typeof AuthenticatedSystemResetRoute
  '/weekly-expenditures': typeof AuthenticatedWeeklyExpendituresRoute
  '/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/benevolent': typeof AuthenticatedBenevolentRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/loans': typeof AuthenticatedLoansRouteWithChildren
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/my-loans': typeof AuthenticatedMyLoansRoute
  '/_authenticated/my-passbook': typeof AuthenticatedMyPassbookRoute
  '/_authenticated/my-savings': typeof AuthenticatedMySavingsRoute
  '/_authenticated/my-weekly': typeof AuthenticatedMyWeeklyRoute
  '/_authenticated/opening-balances': typeof AuthenticatedOpeningBalancesRoute
  '/_authenticated/passbook': typeof AuthenticatedPassbookRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/savings': typeof AuthenticatedSavingsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/system-reset': typeof AuthenticatedSystemResetRoute
  '/_authenticated/weekly-expenditures': typeof AuthenticatedWeeklyExpendituresRoute
  '/_authenticated/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/announcements'
    | '/audit'
    | '/benevolent'
    | '/collections'
    | '/dashboard'
    | '/loans'
    | '/members'
    | '/my-loans'
    | '/my-passbook'
    | '/my-savings'
    | '/my-weekly'
    | '/opening-balances'
    | '/passbook'
    | '/reports'
    | '/savings'
    | '/settings'
    | '/system-reset'
    | '/weekly-expenditures'
    | '/loans/$loanId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/announcements'
    | '/audit'
    | '/benevolent'
    | '/collections'
    | '/dashboard'
    | '/loans'
    | '/members'
    | '/my-loans'
    | '/my-passbook'
    | '/my-savings'
    | '/my-weekly'
    | '/opening-balances'
    | '/passbook'
    | '/reports'
    | '/savings'
    | '/settings'
    | '/system-reset'
    | '/weekly-expenditures'
    | '/loans/$loanId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/announcements'
    | '/_authenticated/audit'
    | '/_authenticated/benevolent'
    | '/_authenticated/collections'
    | '/_authenticated/dashboard'
    | '/_authenticated/loans'
    | '/_authenticated/members'
    | '/_authenticated/my-loans'
    | '/_authenticated/my-passbook'
    | '/_authenticated/my-savings'
    | '/_authenticated/my-weekly'
    | '/_authenticated/opening-balances'
    | '/_authenticated/passbook'
    | '/_authenticated/reports'
    | '/_authenticated/savings'
    | '/_authenticated/settings'
    | '/_authenticated/system-reset'
    | '/_authenticated/weekly-expenditures'
    | '/_authenticated/loans/$loanId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weekly-expenditures': {
      id: '/_authenticated/weekly-expenditures'
      path: '/weekly-expenditures'
      fullPath: '/weekly-expenditures'
      preLoaderRoute: typeof AuthenticatedWeeklyExpendituresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system-reset': {
      id: '/_authenticated/system-reset'
      path: '/system-reset'
      fullPath: '/system-reset'
      preLoaderRoute: typeof AuthenticatedSystemResetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/savings': {
      id: '/_authenticated/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof AuthenticatedSavingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/passbook': {
      id: '/_authenticated/passbook'
      path: '/passbook'
      fullPath: '/passbook'
      preLoaderRoute: typeof AuthenticatedPassbookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opening-balances': {
      id: '/_authenticated/opening-balances'
      path: '/opening-balances'
      fullPath: '/opening-balances'
      preLoaderRoute: typeof AuthenticatedOpeningBalancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-weekly': {
      id: '/_authenticated/my-weekly'
      path: '/my-weekly'
      fullPath: '/my-weekly'
      preLoaderRoute: typeof AuthenticatedMyWeeklyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-savings': {
      id: '/_authenticated/my-savings'
      path: '/my-savings'
      fullPath: '/my-savings'
      preLoaderRoute: typeof AuthenticatedMySavingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-passbook': {
      id: '/_authenticated/my-passbook'
      path: '/my-passbook'
      fullPath: '/my-passbook'
      preLoaderRoute: typeof AuthenticatedMyPassbookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-loans': {
      id: '/_authenticated/my-loans'
      path: '/my-loans'
      fullPath: '/my-loans'
      preLoaderRoute: typeof AuthenticatedMyLoansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/benevolent': {
      id: '/_authenticated/benevolent'
      path: '/benevolent'
      fullPath: '/benevolent'
      preLoaderRoute: typeof AuthenticatedBenevolentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans/$loanId': {
      id: '/_authenticated/loans/$loanId'
      path: '/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof AuthenticatedLoansLoanIdRouteImport
      parentRoute: typeof AuthenticatedLoansRoute
    }
  }
}

interface AuthenticatedLoansRouteChildren {
  AuthenticatedLoansLoanIdRoute: typeof AuthenticatedLoansLoanIdRoute
}

const AuthenticatedLoansRouteChildren: AuthenticatedLoansRouteChildren = {
  AuthenticatedLoansLoanIdRoute: AuthenticatedLoansLoanIdRoute,
}

const AuthenticatedLoansRouteWithChildren =
  AuthenticatedLoansRoute._addFileChildren(AuthenticatedLoansRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBenevolentRoute: typeof AuthenticatedBenevolentRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRouteWithChildren
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedMyLoansRoute: typeof AuthenticatedMyLoansRoute
  AuthenticatedMyPassbookRoute: typeof AuthenticatedMyPassbookRoute
  AuthenticatedMySavingsRoute: typeof AuthenticatedMySavingsRoute
  AuthenticatedMyWeeklyRoute: typeof AuthenticatedMyWeeklyRoute
  AuthenticatedOpeningBalancesRoute: typeof AuthenticatedOpeningBalancesRoute
  AuthenticatedPassbookRoute: typeof AuthenticatedPassbookRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSavingsRoute: typeof AuthenticatedSavingsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSystemResetRoute: typeof AuthenticatedSystemResetRoute
  AuthenticatedWeeklyExpendituresRoute: typeof AuthenticatedWeeklyExpendituresRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBenevolentRoute: AuthenticatedBenevolentRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLoansRoute: AuthenticatedLoansRouteWithChildren,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedMyLoansRoute: AuthenticatedMyLoansRoute,
  AuthenticatedMyPassbookRoute: AuthenticatedMyPassbookRoute,
  AuthenticatedMySavingsRoute: AuthenticatedMySavingsRoute,
  AuthenticatedMyWeeklyRoute: AuthenticatedMyWeeklyRoute,
  AuthenticatedOpeningBalancesRoute: AuthenticatedOpeningBalancesRoute,
  AuthenticatedPassbookRoute: AuthenticatedPassbookRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSavingsRoute: AuthenticatedSavingsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSystemResetRoute: AuthenticatedSystemResetRoute,
  AuthenticatedWeeklyExpendituresRoute: AuthenticatedWeeklyExpendituresRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
